//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Article w post info</summary>
	[PublishedContentModel("articleWPostInfo")]
	public partial class ArticleWpostInfo : PublishedContentModel, IBaseArticle
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "articleWPostInfo";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ArticleWpostInfo(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ArticleWpostInfo, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Author
		///</summary>
		[ImplementPropertyType("author")]
		public object Author
		{
			get { return this.GetPropertyValue("author"); }
		}

		///<summary>
		/// Postdate
		///</summary>
		[ImplementPropertyType("postdate")]
		public DateTime Postdate
		{
			get { return this.GetPropertyValue<DateTime>("postdate"); }
		}

		///<summary>
		/// Article cover image: Full size image
		///</summary>
		[ImplementPropertyType("articleCoverImage")]
		public IPublishedContent ArticleCoverImage
		{
			get { return Umbraco.Web.PublishedContentModels.BaseArticle.GetArticleCoverImage(this); }
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public IHtmlString Content
		{
			get { return Umbraco.Web.PublishedContentModels.BaseArticle.GetContent(this); }
		}

		///<summary>
		/// Headline
		///</summary>
		[ImplementPropertyType("headline")]
		public string Headline
		{
			get { return Umbraco.Web.PublishedContentModels.BaseArticle.GetHeadline(this); }
		}

		///<summary>
		/// Link button
		///</summary>
		[ImplementPropertyType("linkButton")]
		public string LinkButton
		{
			get { return Umbraco.Web.PublishedContentModels.BaseArticle.GetLinkButton(this); }
		}
	}
}
